
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module msp430de1soc(
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	input 		     [3:0]		KEY,
	output		     [9:0]		LEDR,
	input 		     [9:0]		SW,
	inout 		    [35:0]		HDRGPIO
);

   reg [23:0] 	      heartbeat;

	// heartbeat indicator
   always @(posedge CLOCK_50, negedge KEY[0])
     if (KEY[0] == 1'b0)
       heartbeat <= 24'b0;
     else
       heartbeat <= heartbeat + 1'b1;
	assign LEDR[0] = heartbeat[23];

	// uart indicator
	wire rs232_0_txd;
	wire rs232_1_txd;	
	wire rs232_0_rxd;
	wire rs232_1_rxd;	
	reg [20:0] uartled_dly;	
	always @(posedge CLOCK_50, negedge KEY[0])
	  if (~KEY[0])  uartled_dly <= 21'h0;
	  else          uartled_dly <= ~(rs232_0_txd & rs232_1_rxd) ?    21'h1 :
	                               (uartled_dly > 0) ? uartled_dly + 21'h1 :
											 21'h0;
   assign LEDR[1] = (uartled_dly > 0) ? 1'b1 : 1'b0;

	// header pin definition
	assign HDRGPIO[0] = rs232_0_rxd; // debug uart tx
	assign HDRGPIO[2] = rs232_0_txd; // debug uart rx	
	assign HDRGPIO[1] = rs232_1_rxd; // debug uart tx
	assign HDRGPIO[3] = rs232_1_txd; // debug uart rx
	
	// core instantiation
	wire              debug_uart_rx;
	wire              debug_uart_tx;
	wire              user_uart_rx;
	wire              user_uart_tx;	
   wire [7:0] 	      p1_din;
   wire [7:0] 	      p1_dout;
   wire [7:0] 	      p1_dout_en;   
   wire [7:0] 	      p2_din;
   wire [7:0] 	      p2_dout;
   wire [7:0] 	      p2_dout_en;   
   wire [7:0] 	      p3_din;
   wire [7:0] 	      p3_dout;
   wire [7:0] 	      p3_dout_en;   
   wire [7:0] 	      p4_din;
   wire [7:0] 	      p4_dout;
   wire [7:0] 	      p4_dout_en;   
   wire [7:0] 	      p5_din;
   wire [7:0] 	      p5_dout;
   wire [7:0] 	      p5_dout_en;   
   wire [7:0] 	      p6_din;
   wire [7:0] 	      p6_dout;
   wire [7:0] 	      p6_dout_en;
   
   mspconnect theconnector(
	                   .clk_clk(CLOCK_50),
	                   .reset_reset_n(KEY[0]),
	                   .rs232_0_external_interface_RXD(rs232_0_rxd),
	                   .rs232_0_external_interface_TXD(rs232_0_txd),
						    .rs232_1_external_interface_RXD(rs232_1_rxd),
	                   .rs232_1_external_interface_TXD(rs232_1_txd));
	
   toplevel t0(
	       .clk_sys(CLOCK_50),
	       .reset_n(KEY[0]),
	       .p1_din(p1_din),
	       .p1_dout_en(p1_dout_en),
	       .p1_dout(p1_dout),
	       .p2_din(p2_din),
	       .p2_dout_en(p2_dout_en),
	       .p2_dout(p2_dout),
	       .p3_din(p3_din),
	       .p3_dout_en(p3_dout_en),
	       .p3_dout(p3_dout),
	       .p4_din(),
	       .p4_dout_en(p4_dout_en),
	       .p4_dout(p4_dout),
	       .p5_din(),
	       .p5_dout_en(p5_dout_en),
	       .p5_dout(p5_dout),
	       .p6_din(),
	       .p6_dout_en(p6_dout_en),
	       .p6_dout(p6_dout),
	       .debug_uart_rx(debug_uart_rx),
	       .debug_uart_tx(debug_uart_tx),
	       .user_uart_rx(user_uart_rx),
	       .user_uart_tx(user_uart_tx));
	
	assign debug_uart_rx = rs232_0_txd;
	assign user_uart_rx  = rs232_1_txd;
	assign rs232_0_rxd   = debug_uart_tx;
	assign rs232_1_rxd   = user_uart_tx;
	
   assign p1_din      = {5'b0,KEY[3],KEY[2],KEY[1]};
   assign p2_din      = SW[ 7:0];
   assign p3_din      = {6'b0, SW[9:8]};
	
   assign LEDR[9:2]   = p1_dout & p1_dout_en;
   
   hexdecoder HEXD0(p3_dout[3:0] & p3_dout_en[3:0], HEX0);
   hexdecoder HEXD1(p3_dout[7:4] & p3_dout_en[7:4], HEX1);
   hexdecoder HEXD2(p4_dout[3:0] & p4_dout_en[3:0], HEX2);
   hexdecoder HEXD3(p4_dout[7:4] & p4_dout_en[7:4], HEX3);
   hexdecoder HEXD4(p5_dout[3:0] & p5_dout_en[3:0], HEX4);
   hexdecoder HEXD5(p5_dout[7:4] & p5_dout_en[7:4], HEX5);

endmodule
